{{ $root:= . }}

apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Release.Name }}-service
spec:
  selector:
{{- include "labels" . | nindent 4 }}
    {{- with .Values.Service}}
    type: {{ .Type }}
    ports:
      - port: {{ .Port }}
        targetPort: {{ .TargetPort }}
        nodePort: {{ .NodePort }}
    {{- end}}    